# =============================================================================
# Kubernetes Namespace
# =============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: drone-dashboard
  labels:
    name: drone-dashboard
    app: drone-dashboard

